name: Actions

on:
  release:
    types: [published]
  pull_request:
  workflow_dispatch:

jobs:
  # release:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [macos-latest]

  Build-Mac-x64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package
        if: github.event_name == 'release' && github.event.action == 'published' 
        run: npm run electron-mac-x64-package

      - name: Zip
        if: github.event_name == 'release' && github.event.action == 'published' 
        uses: thedoctor0/zip-release@main
        id: create_release
        with:
          type: 'zip'
          path: './idn-admin-console-darwin-x64'
          filename: 'idn-admin-console-darwin-x64.zip'
          exclusions: '*.git* /*node_modules/* /*.angular/* /idn-admin-console-darwin-x64/version'

      - name: Upload to Release
        if: github.event_name == 'release' && github.event.action == 'published' 
        uses: svenstaro/upload-release-action@v2
        with:
          file: idn-admin-console-darwin-x64.zip

  Build-Windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package
        if: github.event_name == 'release' && github.event.action == 'published' 
        run: npm run electron-win-x64-package

      - name: Zip
        if: github.event_name == 'release' && github.event.action == 'published' 
        uses: thedoctor0/zip-release@main
        id: create_release
        with:
          type: 'zip'
          path: './idn-admin-console-win32-x64'
          filename: 'idn-admin-console-win32-x64.zip'
          exclusions: '*.git* /*node_modules/* /*.angular/* /idn-admin-console-win32-x64/version'

      - name: Upload to Release
        if: github.event_name == 'release' && github.event.action == 'published' 
        uses: svenstaro/upload-release-action@v2
        with:
          file: idn-admin-console-win32-x64.zip

  Build-Linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package
        if: github.event_name == 'release' && github.event.action == 'published' 
        run: npm run electron-linux-x64-package

      - name: Zip
        if: github.event_name == 'release' && github.event.action == 'published' 
        uses: thedoctor0/zip-release@main
        id: create_release
        with:
          type: 'zip'
          path: './idn-admin-console-linux-x64'
          filename: 'idn-admin-console-linux-x64'
          exclusions: '*.git* /*node_modules/* /*.angular/* /idn-admin-console-linux-x64/version'

      - name: Upload to Release
        if: github.event_name == 'release' && github.event.action == 'published' 
        uses: svenstaro/upload-release-action@v2
        with:
          file: idn-admin-console-linux-x64.zip

  Build-Docker-Image:
      runs-on: ubuntu-latest 
      steps: 
        - name: Checkout
          uses: actions/checkout@v3
          with:
            persist-credentials: false

        - name: Use HTTPS authentication
          uses: GuillaumeFalourd/SSH-to-HTTPS@v1

        - name: Extract Build Version and set it to VER env var
          run: |
            echo "VER=$(jq -r '.version' package.json)" >> $GITHUB_ENV

        - name: Build Test Package
          if: github.event_name != 'release' 
          uses: docker/build-push-action@v4
          with:
            push: false
            tags: |
              ${{ secrets.DOCKERHUB_REPO }}:latest
              ${{ secrets.DOCKERHUB_REPO }}:${{ env.VER }}

        - name: Login to Docker Hub
          if: github.event_name == 'release' && github.event.action == 'published' 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Deploy to Docker Hub
          if: github.event_name == 'release' && github.event.action == 'published' 
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_REPO }}:latest
              ${{ secrets.DOCKERHUB_REPO }}:${{ env.VER }}

# Build-Mac-arm64:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         persist-credentials: false

  #     - name: Use HTTPS authentication
  #       uses: GuillaumeFalourd/SSH-to-HTTPS@v1

  #     - name: Install Node and NPM
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18.15.0

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Build
  #       run: npm run build

  #     - name: Package
  #       run: npm run electron-mac-arm64-package

  #     - name: Zip
  #       uses: thedoctor0/zip-release@main
  #       id: create_release
  #       with:
  #         type: 'zip'
  #         path: './idn-admin-console-darwin-arm64'
  #         filename: 'idn-admin-console-darwin-arm64.zip'
  #         exclusions: '*.git* /*node_modules/* /*.angular/* /idn-admin-console-darwin-arm64/version'

  #     - name: Upload to Release
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         file: idn-admin-console-darwin-arm64.zip