name: Docker Image CI

on: [workflow_dispatch]
#  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Reconfigure Git to use HTTPS authentication
        uses: GuillaumeFalourd/SSH-to-HTTPS@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18.15

     # - name: Install Dependencies
    #    run: npm install

    #  - name: Build
    #    run: npm run build-prod
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest

#      - name: Docker Login
 #       run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
#          
 #     - name: Build the Docker image # push The image to the docker hub
 #       run: docker build . --tag $DOCKERHUB_REPO:latest

   #   - name: Docker Push
     #   run: docker push $DOCKERHUB_REPO:latest
        
      # -  name: Login to DockerHub
      #    uses: docker/login-action@v2
      #    with:
      #      username: ${{ secrets.DOCKERHUB_USERNAME }}
      #      password: ${{ secrets.DOCKERHUB_TOKEN }}
           
      # - name: Build and push
      #   uses: actions/checkout@v3
      #   with:
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_REPO }}:latest


 
          
  #    - uses: actions/checkout@v3
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
